### ISSUE TITLE
[Explorer/Front] Transaction Detail 페이지 UI

### ISSUE THREAD

**Issue by joykim93** [codestates/BTAFinalProject-04#3]
### ISSUE
- Blockchain Explorer - Transaction Detail 페이지 UI 개발 (특정 Transaction을 선택했을 때 Display 되는 페이지)

### TODO
1. [ ] Transaction Detail 페이지 UI 개발 (Overview)
2. [ ] Transaction Detail 페이지 UI 개발 (Logs)
3. [ ] Transaction Detail 페이지 UI 개발 (Stats)

### `6h`
