### ISSUE TITLE
[Explorer/Front] Smart Contract 페이지 UI

### ISSUE THREAD

**Issue by joykim93** [codestates/BTAFinalProject-04#4]
### ISSUE
- Blockchain Explorer - Smart Contract 페이지 UI 개발 (특정 Smart Contract을 선택했을 때 Display 되는 페이지)

### TODO
1. [ ] Smart Contract 메인 페이지 UI 개발
2. [ ] Smart Contract 메인 페이지 - Transaction Tab UI 개발
3. [ ] Smart Contract 메인 페이지 - Internal Txns Tab UI 개발
4. [ ] Smart Contract 메인 페이지 - Erc20 Token Txns Tab UI 개발
5. [ ] Smart Contract 메인 페이지 - Events Tab UI 개발
6. [ ] Smart Contract 메인 페이지 - Produced Blocks Tab UI 개발

### `6h`
